export const teachersData = [
  {
    id: 1,
    name: "Dr. Rajesh Kumar",
    teacherId: "T001",
    email: "rajesh.kumar@university.edu",
    department: "SOT",
    designation: "Professor",
    specialization: "Computer Science",
    experience: 15,
    qualification: "Ph.D. in Computer Science",
    phone: "+91-9876543210",
  },
  {
    id: 2,
    name: "Prof. Sunita Agarwal",
    teacherId: "T002",
    email: "sunita.agarwal@university.edu",
    department: "SOM",
    designation: "Associate Professor",
    specialization: "Management Studies",
    experience: 12,
    qualification: "Ph.D. in Business Administration",
    phone: "+91-9876543211",
  },
  {
    id: 3,
    name: "Dr. Amit Sharma",
    teacherId: "T003",
    email: "amit.sharma@university.edu",
    department: "SOT",
    designation: "Assistant Professor",
    specialization: "Mechanical Engineering",
    experience: 8,
    qualification: "Ph.D. in Mechanical Engineering",
    phone: "+91-9876543212",
  },
  {
    id: 4,
    name: "Prof. Meera Nair",
    teacherId: "T004",
    email: "meera.nair@university.edu",
    department: "SOH",
    designation: "Professor",
    specialization: "English Literature",
    experience: 18,
    qualification: "Ph.D. in English Literature",
    phone: "+91-9876543213",
  },
  {
    id: 5,
    name: "Dr. Vikash Gupta",
    teacherId: "T005",
    email: "vikash.gupta@university.edu",
    department: "SOT",
    designation: "Associate Professor",
    specialization: "Electrical Engineering",
    experience: 10,
    qualification: "Ph.D. in Electrical Engineering",
    phone: "+91-9876543214",
  },
  {
    id: 6,
    name: "Prof. Kavitha Reddy",
    teacherId: "T006",
    email: "kavitha.reddy@university.edu",
    department: "SOT",
    designation: "Assistant Professor",
    specialization: "Biotechnology",
    experience: 6,
    qualification: "Ph.D. in Biotechnology",
    phone: "+91-9876543215",
  },
  {
    id: 7,
    name: "Dr. Arjun Patel",
    teacherId: "T007",
    email: "arjun.patel@university.edu",
    department: "SOM",
    designation: "Associate Professor",
    specialization: "Finance & Accounting",
    experience: 14,
    qualification: "Ph.D. in Finance",
    phone: "+91-9876543216",
  },
  {
    id: 8,
    name: "Prof. Deepika Singh",
    teacherId: "T008",
    email: "deepika.singh@university.edu",
    department: "SOH",
    designation: "Professor",
    specialization: "Psychology",
    experience: 20,
    qualification: "Ph.D. in Psychology",
    phone: "+91-9876543217",
  },
  {
    id: 9,
    name: "Dr. Ravi Malhotra",
    teacherId: "T009",
    email: "ravi.malhotra@university.edu",
    department: "SOT",
    designation: "Assistant Professor",
    specialization: "Information Technology",
    experience: 5,
    qualification: "Ph.D. in Information Technology",
    phone: "+91-9876543218",
  },
  {
    id: 10,
    name: "Prof. Priya Joshi",
    teacherId: "T010",
    email: "priya.joshi@university.edu",
    department: "SOH",
    designation: "Associate Professor",
    specialization: "Mathematics",
    experience: 11,
    qualification: "Ph.D. in Mathematics",
    phone: "+91-9876543219",
  },
];
