export const academicData = [
  {
    semester: 1,
    courses: [
      {
        name: "dsa",
        exams: {
          fortnightlyTest: [
            {
              test: "ft1",
              maxMarks: 100,
              studentMarks: 85,
              classRank: 5,
              overallRank: 12,
            },
            {
              test: "ft2",
              maxMarks: 100,
              studentMarks: 78,
              classRank: 8,
              overallRank: 25,
            },
            {
              test: "ft3",
              maxMarks: 100,
              studentMarks: 92,
              classRank: 2,
              overallRank: 8,
            },
            {
              test: "ft4",
              maxMarks: 100,
              studentMarks: 74,
              classRank: 12,
              overallRank: 35,
            },
            {
              test: "ft5",
              maxMarks: 100,
              studentMarks: 88,
              classRank: 4,
              overallRank: 15,
            },
            {
              test: "ft6",
              maxMarks: 100,
              studentMarks: 81,
              classRank: 7,
              overallRank: 22,
            },
            {
              test: "ft7",
              maxMarks: 100,
              studentMarks: 95,
              classRank: 1,
              overallRank: 3,
            },
            {
              test: "ft8",
              maxMarks: 100,
              studentMarks: 76,
              classRank: 10,
              overallRank: 28,
            },
            {
              test: "ft9",
              maxMarks: 100,
              studentMarks: 89,
              classRank: 3,
              overallRank: 11,
            },
            {
              test: "ft10",
              maxMarks: 100,
              studentMarks: 83,
              classRank: 6,
              overallRank: 18,
            },
            {
              test: "ft11",
              maxMarks: 100,
              studentMarks: 77,
              classRank: 9,
              overallRank: 26,
            },
            {
              test: "ft12",
              maxMarks: 100,
              studentMarks: 91,
              classRank: 2,
              overallRank: 7,
            },
          ],
          internalAssessment: [
            {
              test: "ia1",
              maxMarks: 50,
              studentMarks: 46,
              classRank: 1,
              overallRank: 3,
            },
            {
              test: "ia2",
              maxMarks: 75,
              studentMarks: 64,
              classRank: 5,
              overallRank: 18,
            },
          ],
          interview: [
            {
              test: "int1",
              maxMarks: 100,
              studentMarks: 93,
              classRank: 1,
              overallRank: 2,
            },
            {
              test: "int2",
              maxMarks: 100,
              studentMarks: 86,
              classRank: 3,
              overallRank: 12,
            },
            {
              test: "int3",
              maxMarks: 100,
              studentMarks: 89,
              classRank: 2,
              overallRank: 8,
            },
            {
              test: "int4",
              maxMarks: 100,
              studentMarks: 91,
              classRank: 1,
              overallRank: 5,
            },
          ],
        },
      },
      {
        name: "webdev",
        exams: {
          fortnightlyTest: [
            {
              test: "ft1",
              maxMarks: 100,
              studentMarks: 74,
              classRank: 14,
              overallRank: 42,
            },
            {
              test: "ft2",
              maxMarks: 100,
              studentMarks: 87,
              classRank: 4,
              overallRank: 15,
            },
            {
              test: "ft3",
              maxMarks: 100,
              studentMarks: 80,
              classRank: 9,
              overallRank: 28,
            },
            {
              test: "ft4",
              maxMarks: 100,
              studentMarks: 92,
              classRank: 2,
              overallRank: 8,
            },
            {
              test: "ft5",
              maxMarks: 100,
              studentMarks: 78,
              classRank: 11,
              overallRank: 35,
            },
            {
              test: "ft6",
              maxMarks: 100,
              studentMarks: 85,
              classRank: 5,
              overallRank: 18,
            },
            {
              test: "ft7",
              maxMarks: 100,
              studentMarks: 83,
              classRank: 7,
              overallRank: 25,
            },
            {
              test: "ft8",
              maxMarks: 100,
              studentMarks: 89,
              classRank: 3,
              overallRank: 12,
            },
            {
              test: "ft9",
              maxMarks: 100,
              studentMarks: 76,
              classRank: 13,
              overallRank: 42,
            },
            {
              test: "ft10",
              maxMarks: 100,
              studentMarks: 91,
              classRank: 2,
              overallRank: 8,
            },
            {
              test: "ft11",
              maxMarks: 100,
              studentMarks: 84,
              classRank: 6,
              overallRank: 22,
            },
            {
              test: "ft12",
              maxMarks: 100,
              studentMarks: 88,
              classRank: 4,
              overallRank: 15,
            },
          ],
          internalAssessment: [
            {
              test: "ia1",
              maxMarks: 50,
              studentMarks: 42,
              classRank: 4,
              overallRank: 15,
            },
            {
              test: "ia2",
              maxMarks: 75,
              studentMarks: 68,
              classRank: 3,
              overallRank: 12,
            },
          ],
          interview: [
            {
              test: "int1",
              maxMarks: 100,
              studentMarks: 87,
              classRank: 2,
              overallRank: 8,
            },
            {
              test: "int2",
              maxMarks: 100,
              studentMarks: 82,
              classRank: 4,
              overallRank: 15,
            },
            {
              test: "int3",
              maxMarks: 100,
              studentMarks: 90,
              classRank: 1,
              overallRank: 8,
            },
          ],
        },
      },
      {
        name: "networking",
        exams: {
          fortnightlyTest: [
            {
              test: "ft1",
              maxMarks: 100,
              studentMarks: 89,
              classRank: 3,
              overallRank: 12,
            },
            {
              test: "ft2",
              maxMarks: 100,
              studentMarks: 94,
              classRank: 1,
              overallRank: 3,
            },
            {
              test: "ft3",
              maxMarks: 100,
              studentMarks: 86,
              classRank: 4,
              overallRank: 15,
            },
            {
              test: "ft4",
              maxMarks: 100,
              studentMarks: 91,
              classRank: 2,
              overallRank: 8,
            },
            {
              test: "ft5",
              maxMarks: 100,
              studentMarks: 88,
              classRank: 3,
              overallRank: 12,
            },
            {
              test: "ft6",
              maxMarks: 100,
              studentMarks: 93,
              classRank: 1,
              overallRank: 5,
            },
            {
              test: "ft7",
              maxMarks: 100,
              studentMarks: 85,
              classRank: 5,
              overallRank: 18,
            },
            {
              test: "ft8",
              maxMarks: 100,
              studentMarks: 90,
              classRank: 2,
              overallRank: 8,
            },
            {
              test: "ft9",
              maxMarks: 100,
              studentMarks: 87,
              classRank: 4,
              overallRank: 15,
            },
            {
              test: "ft10",
              maxMarks: 100,
              studentMarks: 95,
              classRank: 1,
              overallRank: 2,
            },
            {
              test: "ft11",
              maxMarks: 100,
              studentMarks: 89,
              classRank: 3,
              overallRank: 12,
            },
            {
              test: "ft12",
              maxMarks: 100,
              studentMarks: 92,
              classRank: 2,
              overallRank: 8,
            },
          ],
          internalAssessment: [
            {
              test: "ia1",
              maxMarks: 50,
              studentMarks: 48,
              classRank: 1,
              overallRank: 2,
            },
            {
              test: "ia2",
              maxMarks: 75,
              studentMarks: 72,
              classRank: 1,
              overallRank: 3,
            },
          ],
          interview: [
            {
              test: "int1",
              maxMarks: 100,
              studentMarks: 96,
              classRank: 1,
              overallRank: 1,
            },
            {
              test: "int2",
              maxMarks: 100,
              studentMarks: 91,
              classRank: 1,
              overallRank: 5,
            },
            {
              test: "int3",
              maxMarks: 100,
              studentMarks: 94,
              classRank: 1,
              overallRank: 2,
            },
            {
              test: "int4",
              maxMarks: 100,
              studentMarks: 89,
              classRank: 2,
              overallRank: 8,
            },
          ],
        },
      },
    ],
  },
  {
    semester: 2,
    courses: [
      {
        name: "os",
        exams: {
          fortnightlyTest: [
            {
              test: "ft1",
              maxMarks: 100,
              studentMarks: 88,
              classRank: 3,
              overallRank: 9,
            },
            {
              test: "ft2",
              maxMarks: 100,
              studentMarks: 91,
              classRank: 2,
              overallRank: 6,
            },
            {
              test: "ft3",
              maxMarks: 100,
              studentMarks: 85,
              classRank: 5,
              overallRank: 12,
            },
          ],
          internalAssessment: [
            {
              test: "ia1",
              maxMarks: 50,
              studentMarks: 45,
              classRank: 2,
              overallRank: 6,
            },
            {
              test: "ia2",
              maxMarks: 75,
              studentMarks: 69,
              classRank: 3,
              overallRank: 10,
            },
          ],
          interview: [
            {
              test: "int1",
              maxMarks: 100,
              studentMarks: 93,
              classRank: 1,
              overallRank: 2,
            },
            {
              test: "int2",
              maxMarks: 100,
              studentMarks: 89,
              classRank: 2,
              overallRank: 5,
            },
          ],
        },
      },
      {
        name: "dbms",
        exams: {
          fortnightlyTest: [
            {
              test: "ft1",
              maxMarks: 100,
              studentMarks: 79,
              classRank: 6,
              overallRank: 18,
            },
            {
              test: "ft2",
              maxMarks: 100,
              studentMarks: 84,
              classRank: 4,
              overallRank: 14,
            },
            {
              test: "ft3",
              maxMarks: 100,
              studentMarks: 90,
              classRank: 2,
              overallRank: 8,
            },
          ],
          internalAssessment: [
            {
              test: "ia1",
              maxMarks: 50,
              studentMarks: 43,
              classRank: 4,
              overallRank: 15,
            },
            {
              test: "ia2",
              maxMarks: 75,
              studentMarks: 66,
              classRank: 5,
              overallRank: 17,
            },
          ],
          interview: [
            {
              test: "int1",
              maxMarks: 100,
              studentMarks: 88,
              classRank: 3,
              overallRank: 10,
            },
            {
              test: "int2",
              maxMarks: 100,
              studentMarks: 85,
              classRank: 4,
              overallRank: 13,
            },
          ],
        },
      },
    ],
  },
  {
    semester: 3,
    courses: [
      {
        name: "ai",
        exams: {
          fortnightlyTest: [
            {
              test: "ft1",
              maxMarks: 100,
              studentMarks: 92,
              classRank: 1,
              overallRank: 3,
            },
            {
              test: "ft2",
              maxMarks: 100,
              studentMarks: 90,
              classRank: 2,
              overallRank: 5,
            },
            {
              test: "ft3",
              maxMarks: 100,
              studentMarks: 87,
              classRank: 3,
              overallRank: 7,
            },
          ],
          internalAssessment: [
            {
              test: "ia1",
              maxMarks: 50,
              studentMarks: 47,
              classRank: 1,
              overallRank: 2,
            },
            {
              test: "ia2",
              maxMarks: 75,
              studentMarks: 70,
              classRank: 2,
              overallRank: 6,
            },
          ],
          interview: [
            {
              test: "int1",
              maxMarks: 100,
              studentMarks: 95,
              classRank: 1,
              overallRank: 1,
            },
            {
              test: "int2",
              maxMarks: 100,
              studentMarks: 91,
              classRank: 2,
              overallRank: 4,
            },
          ],
        },
      },
      {
        name: "ml",
        exams: {
          fortnightlyTest: [
            {
              test: "ft1",
              maxMarks: 100,
              studentMarks: 81,
              classRank: 5,
              overallRank: 13,
            },
            {
              test: "ft2",
              maxMarks: 100,
              studentMarks: 83,
              classRank: 4,
              overallRank: 11,
            },
            {
              test: "ft3",
              maxMarks: 100,
              studentMarks: 88,
              classRank: 3,
              overallRank: 9,
            },
          ],
          internalAssessment: [
            {
              test: "ia1",
              maxMarks: 50,
              studentMarks: 41,
              classRank: 5,
              overallRank: 16,
            },
            {
              test: "ia2",
              maxMarks: 75,
              studentMarks: 65,
              classRank: 6,
              overallRank: 18,
            },
          ],
          interview: [
            {
              test: "int1",
              maxMarks: 100,
              studentMarks: 89,
              classRank: 3,
              overallRank: 8,
            },
            {
              test: "int2",
              maxMarks: 100,
              studentMarks: 87,
              classRank: 4,
              overallRank: 10,
            },
          ],
        },
      },
    ],
  },
  {
    semester: 4,
    courses: [
      {
        name: "cloud",
        exams: {
          fortnightlyTest: [
            {
              test: "ft1",
              maxMarks: 100,
              studentMarks: 93,
              classRank: 1,
              overallRank: 2,
            },
            {
              test: "ft2",
              maxMarks: 100,
              studentMarks: 88,
              classRank: 2,
              overallRank: 5,
            },
            {
              test: "ft3",
              maxMarks: 100,
              studentMarks: 90,
              classRank: 1,
              overallRank: 4,
            },
          ],
          internalAssessment: [
            {
              test: "ia1",
              maxMarks: 50,
              studentMarks: 46,
              classRank: 2,
              overallRank: 5,
            },
            {
              test: "ia2",
              maxMarks: 75,
              studentMarks: 72,
              classRank: 1,
              overallRank: 3,
            },
          ],
          interview: [
            {
              test: "int1",
              maxMarks: 100,
              studentMarks: 95,
              classRank: 1,
              overallRank: 1,
            },
            {
              test: "int2",
              maxMarks: 100,
              studentMarks: 90,
              classRank: 2,
              overallRank: 4,
            },
          ],
        },
      },
      {
        name: "cybersec",
        exams: {
          fortnightlyTest: [
            {
              test: "ft1",
              maxMarks: 100,
              studentMarks: 86,
              classRank: 4,
              overallRank: 10,
            },
            {
              test: "ft2",
              maxMarks: 100,
              studentMarks: 84,
              classRank: 5,
              overallRank: 12,
            },
            {
              test: "ft3",
              maxMarks: 100,
              studentMarks: 89,
              classRank: 3,
              overallRank: 7,
            },
          ],
          internalAssessment: [
            {
              test: "ia1",
              maxMarks: 50,
              studentMarks: 42,
              classRank: 5,
              overallRank: 14,
            },
            {
              test: "ia2",
              maxMarks: 75,
              studentMarks: 67,
              classRank: 4,
              overallRank: 10,
            },
          ],
          interview: [
            {
              test: "int1",
              maxMarks: 100,
              studentMarks: 88,
              classRank: 3,
              overallRank: 6,
            },
            {
              test: "int2",
              maxMarks: 100,
              studentMarks: 85,
              classRank: 5,
              overallRank: 9,
            },
          ],
        },
      },
    ],
  },
];
