export const studentData = [
  {
    id: 1,
    name: "Priya Sharma",
    studentId: "21CS001",
    email: "priya.sharma@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOT",
    cgpa: 8.5,
  },
  {
    id: 2,
    name: "Arjun Patel",
    studentId: "22ME015",
    email: "arjun.patel@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOT",
    cgpa: 7.8,
  },
  {
    id: 3,
    name: "Kavya Reddy",
    studentId: "21BT003",
    email: "kavya.reddy@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOT",
    cgpa: 9.1,
  },
  {
    id: 4,
    name: "Rahul Gupta",
    studentId: "22BA007",
    email: "rahul.gupta@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOM",
    cgpa: 8.2,
  },
  {
    id: 5,
    name: "Anisha Singh",
    studentId: "21EN012",
    email: "anisha.singh@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOH",
    cgpa: 8.7,
  },
  {
    id: 6,
    name: "Vikram Yadav",
    studentId: "22CS025",
    email: "vikram.yadav@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOT",
    cgpa: 8.9,
  },
  {
    id: 7,
    name: "Deepika Nair",
    studentId: "21EC018",
    email: "deepika.nair@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOT",
    cgpa: 8.4,
  },
  {
    id: 8,
    name: "Aditya Joshi",
    studentId: "22FM009",
    email: "aditya.joshi@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOM",
    cgpa: 7.9,
  },
  {
    id: 9,
    name: "Sneha Iyer",
    studentId: "21PS021",
    email: "sneha.iyer@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOH",
    cgpa: 8.8,
  },
  {
    id: 10,
    name: "Karan Malhotra",
    studentId: "22IT014",
    email: "karan.malhotra@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOT",
    cgpa: 8.1,
  },
  {
    id: 11,
    name: "Riya Agarwal",
    studentId: "21MA006",
    email: "riya.agarwal@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOH",
    cgpa: 8.6,
  },
  {
    id: 12,
    name: "Siddharth Kapoor",
    studentId: "22EE013",
    email: "siddharth.kapoor@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOT",
    cgpa: 8.3,
  },
  {
    id: 13,
    name: "Meera Chandra",
    studentId: "21AC005",
    email: "meera.chandra@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOM",
    cgpa: 8.9,
  },
  {
    id: 14,
    name: "Rohit Verma",
    studentId: "22CE019",
    email: "rohit.verma@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOT",
    cgpa: 7.7,
  },
  {
    id: 15,
    name: "Pooja Bhatt",
    studentId: "21HS011",
    email: "pooja.bhatt@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOH",
    cgpa: 8.5,
  },
  // Additional students
  {
    id: 16,
    name: "Neha Desai",
    studentId: "22PH008",
    email: "neha.desai@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOH",
    cgpa: 8.0,
  },
  {
    id: 17,
    name: "Varun Khanna",
    studentId: "21CH017",
    email: "varun.khanna@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOT",
    cgpa: 8.7,
  },
  {
    id: 18,
    name: "Tanvi Mehta",
    studentId: "22MT022",
    email: "tanvi.mehta@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOM",
    cgpa: 7.5,
  },
  {
    id: 19,
    name: "Rajat Oberoi",
    studentId: "21CS024",
    email: "rajat.oberoi@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOT",
    cgpa: 9.0,
  },
  {
    id: 20,
    name: "Ishaani Banerjee",
    studentId: "22BT016",
    email: "ishaani.banerjee@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOT",
    cgpa: 8.4,
  },
  {
    id: 21,
    name: "Aryan Saxena",
    studentId: "21ME020",
    email: "aryan.saxena@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOT",
    cgpa: 8.2,
  },
  {
    id: 22,
    name: "Divya Choudhary",
    studentId: "22EC023",
    email: "divya.choudhary@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOT",
    cgpa: 8.6,
  },
  {
    id: 23,
    name: "Kunal Rao",
    studentId: "21IT030",
    email: "kunal.rao@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOT",
    cgpa: 8.9,
  },
  {
    id: 24,
    name: "Shreya Menon",
    studentId: "22MA027",
    email: "shreya.menon@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOH",
    cgpa: 8.1,
  },
  {
    id: 25,
    name: "Vivek Nanda",
    studentId: "21CE029",
    email: "vivek.nanda@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOT",
    cgpa: 8.3,
  },
  {
    id: 26,
    name: "Anjali Srinivasan",
    studentId: "22HS028",
    email: "anjali.srinivasan@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOH",
    cgpa: 8.7,
  },
  {
    id: 27,
    name: "Harsh Vardhan",
    studentId: "21FM032",
    email: "harsh.vardhan@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOM",
    cgpa: 7.8,
  },
  {
    id: 28,
    name: "Nandini Kapoor",
    studentId: "22PS033",
    email: "nandini.kapoor@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOH",
    cgpa: 9.0,
  },
  {
    id: 29,
    name: "Pranav Iyer",
    studentId: "21EE035",
    email: "pranav.iyer@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOT",
    cgpa: 8.5,
  },
  {
    id: 30,
    name: "Swati Joshi",
    studentId: "22CH034",
    email: "swati.joshi@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOT",
    cgpa: 8.2,
  },
  {
    id: 31,
    name: "Yash Malhotra",
    studentId: "21MT036",
    email: "yash.malhotra@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOM",
    cgpa: 8.0,
  },
  {
    id: 32,
    name: "Zoya Khan",
    studentId: "22AC037",
    email: "zoya.khan@student.edu",
    batch: "2022-2026",
    semester: "6th",
    department: "SOM",
    cgpa: 8.8,
  },
  {
    id: 33,
    name: "Abhishek Verma",
    studentId: "21PH038",
    email: "abhishek.verma@student.edu",
    batch: "2021-2025",
    semester: "8th",
    department: "SOH",
    cgpa: 8.6,
  },
];
